=== kwilkos/cxf/common/src/main/resources/schemas/configuration/metadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://cxf.apache.org/configuration/metadata" targetNamespace="http://cxf.apache.org/configuration/metadata" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="config" type="tns:configType">
		<xs:annotation>
			<xs:documentation>Describes the complete set of configuration items in a component</xs:documentation>
		</xs:annotation>
		<xs:unique name="nameConstraint">
			<xs:selector xpath="./tns:configItem/tns:name"/>
			<xs:field xpath="."/>
		</xs:unique>
	</xs:element>
	<xs:complexType name="configType">
		<xs:sequence>
			<xs:element name="configImport" type="tns:importType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="configItem" type="tns:configItemType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="namespace" type="xs:anyURI" use="required"/>
		<xs:attribute name="parentNamespace" type="xs:anyURI" use="optional"/>
	</xs:complexType>
	<xs:complexType name="importType">
		<xs:attribute name="namespace" type="xs:anyURI" use="required"/>
		<xs:attribute name="location" type="xs:anyURI" use="required"/>
	</xs:complexType>
	<xs:complexType name="configItemType">
		<xs:annotation>
			<xs:documentation>Describes an individual configuration item</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="tns:nameType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="type" type="tns:typeType" minOccurs="1" maxOccurs="1" />
			<xs:element name="description" type="tns:descriptionType" nillable="true" minOccurs="0"/>
			<xs:element name="lifecyclePolicy" type="tns:lifecyclePolicyType" nillable="false" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="lifecyclePolicyType">
		<xs:annotation>
			<xs:documentation>Specifies if and when the value of a configuration item can be modified</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="static"/>
			<xs:enumeration value="process"/>
			<xs:enumeration value="bus"/>
			<xs:enumeration value="dynamic"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
		    <xs:pattern value="\S+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="typeType">
		<xs:restriction base="xs:string">
		    <xs:pattern value="\S+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="descriptionType">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== kwilkos/cxf/test/unit/org/objectweb/celtix/bus/configuration/resources/top.xml
<?xml version="1.0" encoding="UTF-8"?>
<cm:config 
    xmlns:cm="http://celtix.objectweb.org/configuration/metadata" 
    xmlns:ct="http://celtix.objectweb.org/configuration/types" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://celtix.objectweb.org/configuration/metadata
    c:/celtix/snapshots/andrea/trunk/src/org/objectweb/celtix/configuration/metadata.xsd">

   <!-- configuration metadata for test component top  -->
   
    <cm:configImport location="/org/objectweb/celtix/configuration/types.xsd" namespace="http://celtix.objectweb.org/configuration/types"/>
    
    <!-- items with default values --> 
    
    <cm:configItem>
		<cm:name>booleanItem</cm:name>
		<cm:type>ct:boolean</cm:type>
		<ct:boolean>true</ct:boolean>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>integerItem</cm:name>
		<cm:type>ct:integer</cm:type>
		<ct:integer>44959</ct:integer>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>longItem</cm:name>
		<cm:type>ct:long</cm:type>
		<ct:long>-99</ct:long>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>doubleItem</cm:name>
		<cm:type>ct:double</cm:type>
		<ct:double>1234.5678</ct:double>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>stringItem</cm:name>
		<cm:type>ct:string</cm:type>
		<ct:string>"Hello World!"</ct:string>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>stringListItem</cm:name>
		<cm:type>ct:stringList</cm:type>
		<ct:stringList>
		    <ct:item>a</ct:item>
		    <ct:item>b</ct:item>
		    <ct:item>c</ct:item>
		</ct:stringList>		
	</cm:configItem>
	
	<!-- items without default values -->
	
	<cm:configItem>
		<cm:name>booleanItemNoDefault</cm:name>
		<cm:type>ct:boolean</cm:type>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>integerItemNoDefault</cm:name>
		<cm:type>ct:integer</cm:type>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>longItemNoDefault</cm:name>
		<cm:type>ct:long</cm:type>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>doubleItemNoDefault</cm:name>
		<cm:type>ct:double</cm:type>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>stringItemNoDefault</cm:name>
		<cm:type>ct:string</cm:type>
	</cm:configItem>
	
	<cm:configItem>
		<cm:name>stringListItemNoDefault</cm:name>
		<cm:type>ct:stringList</cm:type>		
	</cm:configItem>
	
</cm:config>

=== kwilkos/cxf/celtix-api/src/main/resources/config-metadata/rm-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<cm:config 
    xmlns:cm="http://celtix.objectweb.org/configuration/metadata" 
    xmlns:std-types="http://celtix.objectweb.org/configuration/types" 
    xmlns:wsrm-conf="http://celtix.objectweb.org/bus/configuration/wsrm"
    xmlns:wsrm-policy="http://schemas.xmlsoap.org/ws/2005/02/rm/policy"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://celtix.objectweb.org/configuration/metadata metadata.xsd"
    namespace="http://celtix.objectweb.org/bus/ws/rm/rm-config">

   <!-- configuration metadata for component RMHandler  -->
   
    <cm:configImport location="schemas/configuration/std-types.xsd" namespace="http://celtix.objectweb.org/configuration/types"/>
    <cm:configImport location="schemas/configuration/wsrm-conf.xsd" namespace="http://celtix.objectweb.org/bus/configuration/wsrm"/>
    <cm:configImport location="schemas/configuration/wsrm-policy.xsd" namespace="http://schemas.xmlsoap.org/ws/2005/02/rm/policy"/>
    
    <cm:configItem>
        <cm:name>rmAssertion</cm:name>
        <cm:type>wsrm-policy:RMAssertionType</cm:type>
        <cm:description>
            Used for configuring an RM source.
        </cm:description>
        <cm:lifecyclePolicy>bus</cm:lifecyclePolicy>
        <wsrm-policy:RMAssertion>
            <wsrm-policy:BaseRetransmissionInterval Milliseconds="3000"/>
            <wsrm-policy:ExponentialBackoff base="2"/>
        </wsrm-policy:RMAssertion>
    </cm:configItem>
    
    <cm:configItem>
        <cm:name>sourcePolicies</cm:name>
        <cm:type>wsrm-conf:sourcePolicyType</cm:type>
        <cm:description>
            Used for configuring an RM source.
        </cm:description>
        <cm:lifecyclePolicy>bus</cm:lifecyclePolicy>
        <!-- no default -->
    </cm:configItem>
    
    <cm:configItem>
        <cm:name>destinationPolicies</cm:name>
        <cm:type>wsrm-conf:destinationPolicyType</cm:type>
        <cm:description>
            Used for configuring an RM destination.
        </cm:description>
        <cm:lifecyclePolicy>bus</cm:lifecyclePolicy>
        <!-- no default -->
    </cm:configItem>
    
    <cm:configItem>
        <cm:name>store</cm:name>
        <cm:type>wsrm-conf:storeType</cm:type>
        <cm:description>
            Used for configuring the RM persistent store.
        </cm:description>
        <cm:lifecyclePolicy>bus</cm:lifecyclePolicy>
        <wsrm-conf:store>
            <wsrm-conf:store-name>File based store</wsrm-conf:store-name>
            <wsrm-conf:store-class>org.objectweb.celtix.bus.ws.rm.persistence.file.RMFileStore</wsrm-conf:store-class>
        </wsrm-conf:store>
    </cm:configItem>
    
</cm:config>
